title: "為一切人，成為一切"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
show_excerpts: false
show_frame: true

navigation:
  - {file: "index.html"}
  - {file: "about.md"}
  - {file: "links.md"}
  - {file: "contact.md"}
  - {title: English, url: "https://poonlonghei.github.io/"}

external:
  - {title: Color, icon: moon, url: "javascript:toggle()"}
  - {title: Github, icon: github, url: "https://github.com/poonlonghei/"}
  - {title: Feed, icon: rss, url: "/feed.xml"}

remote_theme: niklasbuschmann/contrast

plugins:
 - jekyll-remote-theme
 - jekyll-feed
 - jektex

future: true
